document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <title>Book Source</title>");
document.writeln("    <link rel=\'stylesheet\' href=\'./css/reset.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'./awesome/css/all.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'./css/head.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'./css/base.css\'>");
document.writeln("    <script src=\'./js/head.js\'></script>");
document.writeln("    ");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("    <div class=\'topwrp\'>");
document.writeln("        <div class=\'search \' id=\'search\'>");
document.writeln("            <a id=\'cancel\' href=\'javascript:;\'>");
document.writeln("                <ul class=\'cancel\'>");
document.writeln("                    <li></li>");
document.writeln("                    <li></li>");
document.writeln("                </ul>");
document.writeln("            </a>");
document.writeln("            <form action=\'\'>");
document.writeln("                <input id=\'put\' type=\'search\' placeholder=\'Search Books...\'>");
document.writeln("                <a id=\'ser\' href=\'javascript:;\'><i class=\'fas fa-search\'></i></a>");
document.writeln("                <div class=\'content\'>");
document.writeln("                    <div>");
document.writeln("                        <input id=\'book\' type=\'radio\' name=\'search\' checked>");
document.writeln("                        <label for=\'book\'>书名</label>");
document.writeln("                    </div>");
document.writeln("                    <div>");
document.writeln("                        <input id=\'arthir\' type=\'radio\' name=\'search\'>");
document.writeln("                        <label for=\'arthir\'>作者</label>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </form>");
document.writeln("        </div>");
document.writeln("");
document.writeln("");
document.writeln("        <div class=\'topwrap\' id=\'minwidth\'>");
document.writeln("            <!-- 设置头部导航样式 -->");
document.writeln("");
document.writeln("");
document.writeln("            <div class=\'wrapper \'>");
document.writeln("                <div class=\'wrap\'>");
document.writeln("                    <ul class=\'menulist\' id=\'menu\'>");
document.writeln("                        <li id=\'one\'></li>");
document.writeln("                        <li id=\'two\'></li>");
document.writeln("                        <li id=\'three\'></li>");
document.writeln("                    </ul>");
document.writeln("                    <ul class=\'list\' id=\'list\'>");
document.writeln("                        <li><a href=\'./Booklist.html\'>书单</a></li>");
document.writeln("                        <li><a href=\'./eseay.html\'>文章</a></li>");                
document.writeln("                        <li><a href=\'./aboutUs.html\'>关于我们</a></li>");
document.writeln("                      ");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div class=\'logo\'>");
document.writeln("                    <a href=\'index.html\'>Book Source</a>");
document.writeln("");
document.writeln("                </div>");
document.writeln("");
document.writeln("");
document.writeln("                <div class=\'user\'>");
document.writeln("                    <a href=\'javascript:;\' id=\'minser\'>");
document.writeln("                        <i class=\'fas fa-search\'></i>");
document.writeln("                    </a>");
document.writeln("");
document.writeln("                    <a href=\'./logoin.html\' id=\'user\'>");
document.writeln("                        <i class=\'fas fa-user\'></i>");
document.writeln("                    </a>");
document.writeln("                    <ul class=\'losign\'>");
document.writeln("                        <li><a href=\'./logoin.html\'>登录</a></li>");
document.writeln("                        <li><a href=\'./注册页面.html\'>注册</a></li>");
document.writeln("                    </ul>");
document.writeln("");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln(" <div class=\'empty\'> </div>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");